//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/!GameAssets/Scripts/Helper/InputAssets/GameInputActionAsset.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameInputActionAsset: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameInputActionAsset()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInputActionAsset"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""fefac3f6-38a0-4135-b773-3917f9b856f6"",
            ""actions"": [
                {
                    ""name"": ""ClickOrPress"",
                    ""type"": ""Button"",
                    ""id"": ""ea46d66c-f786-499a-9c03-fe0f324ecc22"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ScrollOrPinch"",
                    ""type"": ""Value"",
                    ""id"": ""ea6d2cb3-7756-4a04-b884-5c84fedd6de7"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DragOrSwipe"",
                    ""type"": ""Value"",
                    ""id"": ""a6e307e7-8651-4ecf-8c23-330bb3b45a94"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""272494c0-8870-4991-9f54-fe4a1f96bcd9"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClickOrPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e19280d2-e55f-4edc-9a45-bae379b892f9"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClickOrPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""576432ba-f296-46e0-8aac-2f591a87cc07"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollOrPinch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Pinch"",
                    ""id"": ""3753f225-ee91-42ef-9098-9fc1b7160222"",
                    ""path"": ""TwoModifiers"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollOrPinch"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""7a6d8201-dcff-45cb-b7b9-18c380def8d7"",
                    ""path"": ""<Touchscreen>/primaryTouch/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollOrPinch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""c3f825fc-f669-4fb6-ac82-302ddd1172c8"",
                    ""path"": ""<Touchscreen>/touch1/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollOrPinch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""17d35e2e-ab3c-43d4-98f6-7e6e5df47323"",
                    ""path"": ""<Touchscreen>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollOrPinch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Mouse"",
                    ""id"": ""99c39b81-61d9-46c0-ab36-81906ff6646f"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DragOrSwipe"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""0fd3cea5-0b56-468d-80a8-b4055e4a3f3b"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DragOrSwipe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Binding"",
                    ""id"": ""6bd30538-2206-408b-803f-fec61219ff87"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DragOrSwipe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Touch"",
                    ""id"": ""060b6161-ed37-4f9c-b3f8-f11d828764c5"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DragOrSwipe"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""4722b12c-4d1b-4e79-9a6d-1a4d5e543f2f"",
                    ""path"": ""<Touchscreen>/touch0/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DragOrSwipe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Binding"",
                    ""id"": ""9d2f8f14-a65b-4e12-a136-8f5754a6c541"",
                    ""path"": ""<Touchscreen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DragOrSwipe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_ClickOrPress = m_Gameplay.FindAction("ClickOrPress", throwIfNotFound: true);
        m_Gameplay_ScrollOrPinch = m_Gameplay.FindAction("ScrollOrPinch", throwIfNotFound: true);
        m_Gameplay_DragOrSwipe = m_Gameplay.FindAction("DragOrSwipe", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
    private readonly InputAction m_Gameplay_ClickOrPress;
    private readonly InputAction m_Gameplay_ScrollOrPinch;
    private readonly InputAction m_Gameplay_DragOrSwipe;
    public struct GameplayActions
    {
        private @GameInputActionAsset m_Wrapper;
        public GameplayActions(@GameInputActionAsset wrapper) { m_Wrapper = wrapper; }
        public InputAction @ClickOrPress => m_Wrapper.m_Gameplay_ClickOrPress;
        public InputAction @ScrollOrPinch => m_Wrapper.m_Gameplay_ScrollOrPinch;
        public InputAction @DragOrSwipe => m_Wrapper.m_Gameplay_DragOrSwipe;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void AddCallbacks(IGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
            @ClickOrPress.started += instance.OnClickOrPress;
            @ClickOrPress.performed += instance.OnClickOrPress;
            @ClickOrPress.canceled += instance.OnClickOrPress;
            @ScrollOrPinch.started += instance.OnScrollOrPinch;
            @ScrollOrPinch.performed += instance.OnScrollOrPinch;
            @ScrollOrPinch.canceled += instance.OnScrollOrPinch;
            @DragOrSwipe.started += instance.OnDragOrSwipe;
            @DragOrSwipe.performed += instance.OnDragOrSwipe;
            @DragOrSwipe.canceled += instance.OnDragOrSwipe;
        }

        private void UnregisterCallbacks(IGameplayActions instance)
        {
            @ClickOrPress.started -= instance.OnClickOrPress;
            @ClickOrPress.performed -= instance.OnClickOrPress;
            @ClickOrPress.canceled -= instance.OnClickOrPress;
            @ScrollOrPinch.started -= instance.OnScrollOrPinch;
            @ScrollOrPinch.performed -= instance.OnScrollOrPinch;
            @ScrollOrPinch.canceled -= instance.OnScrollOrPinch;
            @DragOrSwipe.started -= instance.OnDragOrSwipe;
            @DragOrSwipe.performed -= instance.OnDragOrSwipe;
            @DragOrSwipe.canceled -= instance.OnDragOrSwipe;
        }

        public void RemoveCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameplayActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);
    public interface IGameplayActions
    {
        void OnClickOrPress(InputAction.CallbackContext context);
        void OnScrollOrPinch(InputAction.CallbackContext context);
        void OnDragOrSwipe(InputAction.CallbackContext context);
    }
}
