//----------------------------------------------------------------------
// Author   : "Ananta Miyoru Wijaya"
//----------------------------------------------------------------------

using UnityEngine;

using MyCampusStory.ResourceSystem;

namespace MyCampusStory.BuildingSystem
{
    /// <summary>
    /// Building scriptableobject for defining purposes only
    /// </summary>
    [CreateAssetMenu(fileName = "Name_BuildingSO", menuName = "ScriptableObjects/BuildingSO")]
    public class BuildingSO : ScriptableObject
    {
        [Tooltip("The base id of the building.")]
        public string BuildingBaseId;
        public string BuildingName;
        
        [TextArea] 
        public string BuildingDescription;
        public int MaxBuildingLevel;
        
        [Tooltip("The stats of the building for each level.")]
        public BuildingStat[] BuildingStatsPerLevel;
    }

    [System.Serializable]
    public struct BuildingStat
    {
        public int BuildingLevelForStat;
        
        [Tooltip("The resources required for upgrading the building to next level.")]
        public BuildingUpgradeRequirement[] BuildingUpgradeRequirements;

        [Tooltip("The resources generated by the building.")]
        public ResourceGenerationStat[] ResourceGenerationStats;
        

        [System.Serializable]
        public struct BuildingUpgradeRequirement
        {
            public ResourceSO RequiredResource;
            public int RequiredResourceAmount;
        }

        [System.Serializable]
        public struct ResourceGenerationStat
        {
            public ResourceSO ResourceToGenerate;
            public int GeneratedResourceAmount;
            public float ResourceGenerationIntervalInSecondsRealTime;
        }
    }
    
}
