//----------------------------------------------------------------------
// Author   : "Ananta Miyoru Wijaya"
//----------------------------------------------------------------------

using System.Collections.Generic;
using UnityEngine;

using MyCampusStory.StandaloneManager;
using MyCampusStory.DataPersistenceSystem;
using MyCampusStory.ResourceSystem;

namespace MyCampusStory.BuildingSystem
{
    public class Building : MonoBehaviour, IDataPersistence, IInteractable
    {
        [System.Serializable]
        public struct BuildingData
        {
            [Tooltip("The base id of the building.")]
            public string BuildingBaseId;
            public string BuildingName;
            
            [TextArea]
            public string BuildingDescription;
        }

        

        [SerializeField] private BuildingData _buildingData;

        [Tooltip("The reference / instance id of the building.")]
        [SerializeField] private string _buildingRefId;
        [SerializeField] private int _maxBuildingLevel;

        [Tooltip("The stats of the building for each level.")]
        [SerializeField] private List<BuildingStat> _buildingStatsPerLevel;

        private bool _isBuildingUnlocked = false;
        private int _currentBuildingLevel = 1;
        private BuildingStat _currentBuildingStat;
        private Dictionary<int, BuildingStat> _buildingStatsPerLevelDictionary;
        private BuildingUpgradeManager _buildingUpgradeManager;

        private void Awake()
        {
            _buildingUpgradeManager = new BuildingUpgradeManager();

            //Initialize building stats dictionary
            foreach (var buildingStat in _buildingStatsPerLevel)
            {
                _buildingStatsPerLevelDictionary.Add(buildingStat.BuildingLevel, buildingStat);
            }

            _currentBuildingStat = _buildingStatsPerLevelDictionary[_currentBuildingLevel];
        }


        public void UpgradeBuilding()
        {
            if(_currentBuildingLevel >= _maxBuildingLevel)
            {
                Debug.Log("Max level reached");
                return;
            }

            if(!_buildingUpgradeManager.TryUpgradingBuilding(_buildingStatsPerLevelDictionary, _currentBuildingStat, _currentBuildingLevel, LevelManager.Instance.ResourceManager))
            {
                Debug.Log("Not enough resources to upgrade");
                return;
            }

            _currentBuildingLevel++;
        }

        public void SaveData(GameData data)
        {
            if(data.PlayerBuildingData.ContainsKey(_buildingRefId))
            {
                data.PlayerBuildingData[_buildingRefId].IsBuildingUnlocked = _isBuildingUnlocked;
                data.PlayerBuildingData[_buildingRefId].CurrentBuildingLevel = _currentBuildingLevel;
            }
            else
            {
                data.PlayerBuildingData.Add(_buildingRefId, new SerializedBuildingData
                {
                    IsBuildingUnlocked = _isBuildingUnlocked,
                    CurrentBuildingLevel = _currentBuildingLevel
                });
            }
        }

        public void LoadData(GameData data)
        {
            if(data.PlayerBuildingData.ContainsKey(_buildingRefId))
            {
                _isBuildingUnlocked = data.PlayerBuildingData[_buildingRefId].IsBuildingUnlocked;
                _currentBuildingLevel = data.PlayerBuildingData[_buildingRefId].CurrentBuildingLevel;
            }
        }

        public void Interact()
        {
            
        }

        [ContextMenu("Generate Building Ref Id")]
        private void GenerateBuildingRefId()
        {
            _buildingRefId = _buildingData.BuildingBaseId + "_" + System.Guid.NewGuid().ToString();
        }
    }

    [System.Serializable]
    public struct BuildingStat
    {
        public int BuildingLevel;
        
        [Tooltip("The resources required for upgrading the building to next level.")]
        public List<BuildingUpgradeRequirement> BuildingUpgradeRequirements;

        [Tooltip("The resources generated by the building.")]
        public List<ResourceGenerationStat> ResourceGenerationStats;
        

        [System.Serializable]
        public struct BuildingUpgradeRequirement
        {
            public ResourceSO RequiredResource;
            public int RequiredResourceAmount;
        }

        [System.Serializable]
        public struct ResourceGenerationStat
        {
            public Resource ResourceToGenerate;
            public int GeneratedResourceAmount;
        }
    }
    
}
