//----------------------------------------------------------------------
// Author   : "Ananta Miyoru Wijaya"
//----------------------------------------------------------------------

using UnityEngine;

using MyCampusStory.ResourceSystem;

namespace MyCampusStory.BuildingSystem
{
    /// <summary>
    /// Building scriptableobject for defining purposes only
    /// </summary>
    [CreateAssetMenu(fileName = "Name_BuildingSO", menuName = "ScriptableObjects/BuildingSO")]
    public class BuildingSO : ScriptableObject
    {
        public string BuildingBaseId;
        public string BuildingName;
   
        [TextArea] 
        public string BuildingDescription;
        public BuildingStat[] BuildingStatsPerLevel;
        
        [HideInInspector]
        public int MaxBuildingLevel => BuildingStatsPerLevel.Length;
    }

    [System.Serializable]
    public struct BuildingStat
    {
        [Tooltip("The resources required for upgrading the building to next level.")]
        public BuildingUpgradeRequirement[] BuildingUpgradeRequirements;

        [Tooltip("The resources generated by the building.")]
        public ResourceGenerationStat[] ResourceGenerationStats;
        

        [System.Serializable]
        public struct BuildingUpgradeRequirement
        {
            public ResourceSO ResourceRequired;
            public int AmountRequired;
        }

        [System.Serializable]
        public struct ResourceGenerationStat
        {
            public ResourceSO ResourceGenerated;
            public int AmountGenerated;
            public float GenerationTimeInterval;
        }
    }
    
}
